### ISSUE TITLE
How to center Instagram embeds?

### ISSUE THREAD

**Issue by nrrb** [vivelohoy/vivelohoy-3.0#145]
Gisela added an Instagram embed to one of her posts:
![image](https://cloud.githubusercontent.com/assets/486230/4280370/95605966-3d2c-11e4-90f4-40e88688518f.png)

The code is:

``` html
<iframe src="//instagram.com/p/s8vP-tI97c/embed/" width="612" height="710" frameborder="0" scrolling="no" allowtransparency="true"></iframe>
```

This appears left-aligned:
![image](https://cloud.githubusercontent.com/assets/486230/4280375/af1c12dc-3d2c-11e4-8de7-6b198fee145d.png)

She would like this to appear centered, but it's not clear how to do this. In Text editing mode, there are no options in the toolbar for centering an element:
![image](https://cloud.githubusercontent.com/assets/486230/4280380/cbd8cb72-3d2c-11e4-8e1e-587b1622928d.png)

In Visual mode there is a center tool in the toolbar and this can be used on the iframe elements:
![image](https://cloud.githubusercontent.com/assets/486230/4280414/550098b2-3d2d-11e4-8ae7-035fb0fe7402.png)

But after saving the post, the elements revert to left justified and there's no evidence of the previous centering action.

**Comment by oriolmendivil** [comment]
you should use CSS for that, I have the same issue, and now I just add some lines there on entry styles... but If you don't have access to that code, you could add inline style like this...
`<style>.instagram-media{margin:0 auto!important;}</style>`
You could replace "0" with any other value... That should works fine ;)

**Comment by PeerRoth** [comment]
I'm working on this too.  If you go to your site that has instagram post embedded and devtools select and hover over it you'll see how many divs there actually are that embed.  What seems to happen is that different sizes of the video are served at different media queries and not only that but there are max and min widths for each.  If you wrap in a centered div and scale down the browser window, the embed ultimately meets it's min-width and becomes uncentered.
