### ISSUE TITLE
Video index does not appear on front page on mobile

### ISSUE THREAD

**Issue by tothebeat** [vivelohoy/vivelohoy-3.0#190]
The video index that is visible on the front page from the desktop is not visible on mobile.

Desktop:
![image](https://cloud.githubusercontent.com/assets/486230/5743713/a1c28cc0-9be0-11e4-8d7d-34b11c401801.png)

Mobile:
![image](https://cloud.githubusercontent.com/assets/486230/5743734/c40a183e-9be0-11e4-9a45-775e7b7524c8.png)

This issue was reported by John Trainor.

Paging @luciovilla to this issue.

**Comment by luciovilla** [comment]
Decided to not display player on mobile for the front page to avoid load time. Video posts are appearing on the front page now and an option in the menu appears now.
