### ISSUE TITLE
Add author meta information to posts

### ISSUE THREAD

**Issue by tothebeat** [vivelohoy/vivelohoy-3.0#49]
Follow Largo's example in their [open-graph.php](https://github.com/INN/Largo/blob/master/inc/open-graph.php) file, to insert metadata in the header of every post attributing the post's author for Google results.

**Comment by luciovilla** [comment]
Yoast SEO already offers this. For Facebook it offers OpenGraph and Cards for Twitter:
https://yoast.com/social-media-optimization-with-wordpress-seo-by-yoast/
